env:
  global:
    - CC_TEST_REPORTER_ID=31e08d0f6a91477f567ca12d6599f1e9ae6553f2b499a2dfdb6efb57606734a4
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
language: ruby
rvm:
  - 2.5.0
  - 2.4.3
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - 2.1

addons:
  chrome: stable
before_install:
  - gem install bundler --pre
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT